#!/usr/bin/env bash

source ./cmd.config

echo ""
echo ""
echo "DEPLOYING TO HOST:" $hostname
echo "DEPLOYING TO DATABASE: " $database
echo ""

for i in ${packages[@]};
do
  echo "DEPLOYING PACKAGE ------------------------------------------------------------" $i
  (cd ./"$i"/ && sqitch deploy)
done
