#!/usr/bin/env bash

source ./cmd.config

echo ""
echo ""
echo "INITIALIZING SQITCH ENGINE"
echo ""

for i in ${packages[@]};
do
  echo "INITIALIZING PACKAGE ------------------------------------------------------------" $i
  (cd ./"$i"/ && cp sqitch.conf.starter sqitch.conf)
done
