#!/usr/bin/env bash
(cd ./schema/org_fn/ && sqitch target add "$@")
(cd ./schema/org/ && sqitch target add "$@")
(cd ./schema/auth_fn/ && sqitch target add "$@")
(cd ./schema/auth/ && sqitch target add "$@")
(cd ./schema/app-roles/ && sqitch target add "$@")

(cd ./core-data/ && sqitch target add "$@")
