#!/usr/bin/env bash

echo ""
echo ""
echo "CONFIGURING SQITCH TARGET"
echo ""

for i in ${packages[@]};
do
  echo "CONFIGURING PACKAGE ------------------------------------------------------------" $i
  (cd ./"$i"/ && sqitch target add "$@")
done
