#!/usr/bin/env bash

echo ""
echo ""
echo "VERIFYING SQITCH DEPLOY"
echo ""

for i in ${packages[@]};
do
  echo "VERIFYING PACKAGE ------------------------------------------------------------" $i
  (cd ./"$i"/ && sqitch verify)
done
